CREATE TABLE student (
	idst INT UNSIGNED NOT NULL AUTO_INCREMENT,
	jmeno VARCHAR(35) CHARACTER SET 'utf8' NOT NULL COLLATE 'utf8_czech_ci',
	prijmeni VARCHAR(50) CHARACTER SET 'utf8' NOT NULL COLLATE 'utf8_czech_ci',
	datum_narozeni DATE NOT NULL,
	PRIMARY KEY (idst)
) ENGINE=InnoDB;

CREATE TABLE skola (
	idsk INT UNSIGNED NOT NULL AUTO_INCREMENT,
	nazev VARCHAR(50) CHARACTER SET 'utf8' NOT NULL COLLATE 'utf8_czech_ci',
	zkratka VARCHAR(10) CHARACTER SET 'utf8' NOT NULL COLLATE 'utf8_czech_ci',
	mesto VARCHAR(35) CHARACTER SET 'utf8' NOT NULL COLLATE 'utf8_czech_ci',
	PRIMARY KEY (idsk),
	UNIQUE(zkratka)
) ENGINE=InnoDB;

CREATE TABLE studium (
	kdo INT UNSIGNED NOT NULL,
	kde INT UNSIGNED NOT NULL,
	od_kdy DATE NOT NULL,
	do_kdy DATE,
	PRIMARY KEY (kdo,kde),
	FOREIGN KEY (kdo) REFERENCES student (idst) ON UPDATE CASCADE,
	FOREIGN KEY (kde) REFERENCES skola (idsk) ON UPDATE CASCADE
) ENGINE=InnoDB;
